### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by MatthewScholefield** [reorx/python-terminal-color#1]
Hi, I'd like to use this in my project but it doesn't have a license. Would you consider publishing this under something like MIT?

Thanks,
Matthew

**Comment by reorx** [comment]
Hi Matthew,

The MIT license has been added to the project, glad you like it :)

P.S. currently this project is Python 2 only (or at least not Python 3 tested), I have a local branch that adds first-class Python 3 support to it, if you don't mind, please wait 1-2 days for that branch merge to master. (I suppose your project is Python 3)

**Comment by reorx** [comment]
Notice: py3 branch has been merged to master, now `color.py` is a Python 3 only script, whereas `color_compat.py` is kept for Python 2/3 compatible use, enjoy.

**Comment by MatthewScholefield** [comment]
Awesome, thanks!
